Physician
talDoFlemis/health_hub pull request #37
Opened 2023-07-02 21:44 UTC by brunobacs

# Description
Physician update: Update/Patch Physician to db ok

2023-07-02 23:57 UTC, talDoFlemis requested changes
Todas são sugestões com exceção da rota da API no Controller e os PreAuthroize no Controller que só o admin pode mexer com o Physician por agora

2023-07-02 23:57 UTC, talDoFlemis commented on backend/src/main/java/com/usguri/health_hub/physician/PhysicianRepository.java
> +    @Query("SELECT p FROM Physician p WHERE p.email =?1")
Você não precisa escrever a `@Query` de cima, o JPA, a biblioteca que a gente está usando para usar o banco de dados, possue uma linguagem interna chamada `Custom Finders`. Basicamente ele gera uma query automática dependendo de como tu escreve a função. Então tu pode simplesmente gerar essa query se tu definir a função como `findByEmail` que ele gera exatamente o que tem no `@Query`

Mais informações [aqui](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-creation)

2023-07-02 23:57 UTC, talDoFlemis commented on backend/src/main/java/com/usguri/health_hub/physician/PhysicianController.java
> +@RequestMapping(path="/physician")
Adicionar o `${apiPrefix}/` antes para manter o padrão de todas as rotas e facilitar para os nossos amigos do frontend. Assim todas as rotas começam com `/api/`

2023-07-02 23:57 UTC, talDoFlemis commented on backend/src/main/java/com/usguri/health_hub/physician/Physician.java
> +    @GeneratedValue(
Se deletar o `SequenceGenerator` e deixar apenas o `GeneratedValue` sem nenhum valor já gera essa sequência para nós automaticamente.

![image](https://github.com/talDoFlemis/health_hub/assets/33133120/90708d71-1eb5-4653-9e43-165b9dacb857)

Esses que terminam com `_sec` foram gerados automaticamente por essa configuração

2023-07-02 23:57 UTC, talDoFlemis commented on backend/src/main/java/com/usguri/health_hub/physician/PhysicianController.java
> +    @Autowired
Se tu usar o `@RequiredArgsConstructor` do lombok ele faz automaticamente o Construtor com os campos que são private final

2023-07-02 23:57 UTC, talDoFlemis commented on backend/src/main/java/com/usguri/health_hub/physician/PhysicianController.java
> +    @PreAuthorize(value = "hasAnyRole('ADMIN', 'PHYSICIAN')")
Das nossas regras de negócio só quem podem criar, deletar e atualizar médico é o admin
![image](https://github.com/talDoFlemis/health_hub/assets/33133120/acea24d5-c7d0-430a-a982-5a6b4235996b)
A única coisa que o médico pode fazer é ver as próprias consultas, mas isso só vai ser implementado quando a gente fizer o `Appointment`

2023-07-04 00:46 UTC, brunobacs commented on backend/src/main/java/com/usguri/health_hub/physician/PhysicianController.java
> +    @Autowired
Aí tira o @Autowired ?

2023-07-04 08:23 UTC, talDoFlemis submitted a review, later dismissed
aprovado

2023-07-04 08:25 UTC, talDoFlemis approved these changes
aprovado

2023-07-04 08:25 UTC, merged